[About]
about = 'Configuration for training of fine grain classifier'

[maintainer]
name = 'Tan Ren Jie'
email = 'renjie.tan91@gmail.com'

[dataset]
name = 'StanfordCarDataset'

[models]
# Supports only resnet18, resnet50, resnet101, resnet50_32x4d, resnet101_32x8d
name = 'resnet18'

[mlflow]
host = '0.0.0.0'
port = '8000'

[training]
epoch = 10

[optimizer]
learning_rate = 1e-3
momentum = 0.9

[lr_scheduler]
# Decay lr by a factor of gamma every step_size
step_size = 7 
gamma = 0.1

